#!/bin/sh
# Start/stop the syslog2mysql daemon.

USER=nagios
GROUP=nagcmd
DAEMON=/usr/local/nagios/contrib/syslog-ng2mysql.pl
FIFO=$(cat $DAEMON |egrep -i '^my \$fifo' |cut -d"=" -f2 |sed 's/"//g; s/;//g')
test -p $FIFO || mkfifo -m 0664 $FIFO
chown $USER:$GROUP $FIFO

test -f $DAEMON || exit 0

case "$1" in
start)	echo -n "Starting syslog2mysql daemon"
        start-stop-daemon --start --user $USER --quiet -m --pidfile /var/run/syslog-ng2mysql.pid --startas $DAEMON -b
        echo "." 
	;;
stop)   echo -n "Stopping syslog2mysql daemon"
        start-stop-daemon --stop --quiet --pidfile /var/run/syslog-ng2mysql.pid  
		killall syslog-ng2mysql.pl     
        echo "."
        ;;
*)	echo "Usage: /etc/init.d/syslogd2mysql start|stop"
        exit 1 
        ;;
esac
exit 0
