CREATE TABLE  "EVENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HOST_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"HOST_ADDRESS" VARCHAR2(255),
	"TYPE" NUMBER(11,0) NOT NULL ENABLE,
	"FACILITY" NUMBER(11,0),
	"PRIORITY" NUMBER(11,0) NOT NULL ENABLE,
	"PROGRAM" VARCHAR2(50) NOT NULL ENABLE,
	"MESSAGE" VARCHAR2(4000) DEFAULT NULL,
	"ACK" NUMBER(*,0) DEFAULT '0',
	"CREATED" DATE DEFAULT NULL,
	"MODIFIED" DATE DEFAULT NULL,
	 CONSTRAINT "PK_EVENT" PRIMARY KEY ("ID") ENABLE
   )
/

CREATE INDEX  "EVENT_ACK" ON  "EVENT" ("ACK")
/

CREATE INDEX  "EVENT_CREATED" ON  "EVENT" ("CREATED")
/

CREATE INDEX  "EVENT_FACILITY" ON  "EVENT" ("FACILITY")
/

CREATE INDEX  "EVENT_FAC_TIME" ON  "EVENT" ("FACILITY", "PRIORITY", "MODIFIED", "ACK")
/

CREATE INDEX  "EVENT_HOST_NAME" ON  "EVENT" ("HOST_NAME")
/

CREATE INDEX  "EVENT_IDX1" ON  "EVENT" ("HOST_NAME", "TYPE", "FACILITY", "PRIORITY")
/

CREATE INDEX  "EVENT_MODIFIED" ON  "EVENT" ("MODIFIED")
/

CREATE INDEX  "EVENT_PRIORITY" ON  "EVENT" ("PRIORITY")
/

CREATE INDEX  "EVENT_TIME" ON  "EVENT" ("CREATED", "MODIFIED", "HOST_NAME", "TYPE")
/

CREATE INDEX  "EVENT_TYPE_IDX" ON  "EVENT" ("FACILITY", "PRIORITY", "PROGRAM", "ACK")
/


