#!/bin/sh
#
# chkconfig: 345 99 01
# description: Icinga network monitor
### BEGIN INIT INFO
# Provides:          syslog-ng2mysql
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: EventDB syslog-ng2mysql Initscript
# Description:       EventDB Syslog to MySQL
### END INIT INFO

USER=icinga
GROUP=icinga
DAEMON=/usr/local/icinga/contrib/syslog-ng2mysql.pl
FIFO=$(cat $DAEMON |egrep -i '^my \$fifo' |cut -d"=" -f2 |sed 's/"//g; s/;//g')
test -p $FIFO || mkfifo -m 0664 $FIFO
chown $USER:$GROUP $FIFO

test -f $DAEMON || exit 0

case "$1" in
start)	echo -n "Starting syslog2mysql daemon"
        $DAEMON --start --user $USER --quiet -m --pidfile /var/run/syslog-ng2mysql.pid --startas $DAEMON -b
        echo "." 
	;;
stop)   echo -n "Stopping syslog2mysql daemon"
        $DAEMON --stop --quiet --pidfile /var/run/syslog-ng2mysql.pid  
		killall syslog-ng2mysql.pl     
        echo "."
        ;;
*)	echo "Usage: /etc/init.d/syslogd2mysql start|stop"
        exit 1 
        ;;
esac
exit 0
