<?php

/**
 * EventDbCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventDbCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventDbCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventDbComments');
    }
}